apiVersion: v2
name: bibli-website
description: A Helm chart for bibli website on Kubernetes

type: application

version: 0.1.0

appVersion: 1.0.0

dependencies:
  - name: mongodb
    version: "7.8.10"
    repository: "@stable"