# GLOBAL
pullPolicy: IfNotPresent

# POSTGRESQL DATABASE
mongodb:
  image:
    registry: docker.io
    repository: mongo
    tag: bionic
  fullnameOverride: bibli-database
  createSecret: true
  mongodbDatabase: books
  mongodbUsername: tibino7
  mongodbPassword: toto
  service:
    port: 27017

# ISBN MICROSERVICE
isbnSrv:
  image: tibino7/isbnsrv
  tag: 1.1.1
  port: 8080
  service:
    name: bibli-isbn-manager
    type: ClusterIP
  replicas: 1

# DJANGO APP
website:
  image: tibino7/bibli-website
  tag: "1.0"
  port: 8000
  service:
    name: bibli-website
    type: ClusterIP
  replicas: 1
  ingress:
    enabled: true
    host: bibli-website.k3s.thulot.fr
    ingressClassName: nginx
    secret: bibli-website-k3s-net-tls
  env:
