# GLOBAL
pullPolicy: IfNotPresent

# POSTGRESQL DATABASE
postgresql:
  image:
    repository: postgresql
    tag: 11.7
  fullnameOverride: bibli-database
  createSecret: true
  postgresqlDatabase: books
  postgresqlUsername: tibino7
  postgresqlPassword: toto
  service:
    port: 5432

# ISBN MICROSERVICE
isbnSrv:
  image: tibino7/isbnsrv
  tag: 1.1.1
  port: 8080
  service:
    name: bibli-isbn-manager
    type: ClusterIP
  replicas: 1

# DJANGO APP
website:
  image: tibino7/bibli-website
  tag: "1.0"
  port: 8000
  service:
    name: bibli-website
    type: ClusterIP
  replicas: 1
  ingress:
    enabled: true
    host: bibli-website.local
    ingressClassName: nginx
  env:
