apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.website.service.name }}
  labels:
    {{- include "bibli-website.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.website.replicas }}
  selector:
    matchLabels:
      {{- include "bibli-website.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bibli-website.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
      - name: {{ .Values.website.service.name }}-init
        image: "{{ .Values.website.image }}:{{ .Values.website.tag }}"
        imagePullPolicy: IfNotPresent
        env:
          - name: POSTGRES_DB
            value: "{{ .Values.postgresql.postgresqlDatabase }}"
          - name: POSTGRES_USER
            value: "{{ .Values.postgresql.postgresqlUsername }}"
          - name: POSTGRES_PWD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.postgresql.fullnameOverride }}
                key: postgresql-password
          - name: POSTGRES_HOST
            value: "{{ .Values.postgresql.fullnameOverride }}"
          - name: POSTGRES_PORT
            value: "5432"
          - name: THIS_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: DJANGO_ALLOWED_HOSTS
            value: "{{ .Values.website.ingress.host }}"
        command:
        - /bin/bash
        - -c
        - sleep 15 &&
          echo "Begin Migration ..." &&
          python3 manage.py makemigrations books &&
          python3 manage.py migrate &&
          python3 manage.py createsuperuserauto --username tibino7 --password toto --preserve --no-input --email 'tibino7@github.com' &&
          echo "Migration Completed" &&
          sleep 10
      containers:
        - name: bibli-website
          image: "{{ .Values.website.image }}:{{ .Values.website.tag }}"
          imagePullPolicy: {{ .Values.pullPolicy }}
          env:
          - name: POSTGRES_HOST
            value: "{{ .Values.postgresql.fullnameOverride }}"
          - name: POSTGRES_PORT
            value: "{{ .Values.postgresql.service.port }}"
          - name: POSTGRES_DB
            value: "{{ .Values.postgresql.postgresqlDatabase }}"
          - name: POSTGRES_USERNAME
            value: "{{ .Values.postgresql.postgresqlUsername }}"
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.postgresql.fullnameOverride }}
                key: postgresql-password
          - name: THIS_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: DJANGO_ALLOWED_HOSTS
            value: "{{ .Values.website.ingress.host }}"
          ports:
            - name: http
              containerPort: {{ .Values.website.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /readiness
              port: http
            initialDelaySeconds: 20
            timeoutSeconds: 5