apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.isbnSrv.service.name }}
  labels:
    {{- include "bibli-website.labels" . | nindent 4 }}
spec:
  type: {{ .Values.isbnSrv.service.type }}
  ports:
    - port: {{ .Values.isbnSrv.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "bibli-website.selectorLabels" . | nindent 4 }}