{{- if .Values.mongo.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mongo.fullnameOverride }}
  labels: 
    {{- include "bibli-database.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
type: Opaque
data:
  {{- if and .Values.mongo.auth.username .Values.mongo.auth.database }}
  {{- if .Values.mongo.auth.password }}
  mongodb-password:  {{ .Values.mongo.auth.password | toString | b64enc | quote }}
  {{- else }}
  mongodb-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
